### ISSUE TITLE
Error running: python setup.py install --build-js

### ISSUE THREAD

**Issue by emiudeh** [Maluuba/bokeh#8]
On running the setup.py (complete) command, I get the following errors:

```
ERROR: 'gulp build' returned the following

---- on stdout:
    

---- on stderr:
    
    /home/udeh/Git/bokeh/bokehjs/node_modules/undertaker/lib/set-task.js:10
      assert(typeof fn === 'function', 'Task function must be specified');
      ^
    AssertionError [ERR_ASSERTION]: Task function must be specified
        at Gulp.set [as _setTask] (/home/udeh/Git/bokeh/bokehjs/node_modules/undertaker/lib/set-task.js:10:3)
        at Gulp.task (/home/udeh/Git/bokeh/bokehjs/node_modules/undertaker/lib/task.js:13:8)
        at Object.<anonymous> (/home/udeh/Git/bokeh/bokehjs/gulp/tasks/build.ts:4:6)
        at Module._compile (module.js:653:30)
        at Module.m._compile (/home/udeh/Git/bokeh/bokehjs/node_modules/ts-node/src/index.ts:392:23)
        at Module._extensions..js (module.js:664:10)
        at Object.require.extensions.(anonymous function) [as .ts] (/home/udeh/Git/bokeh/bokehjs/node_modules/ts-node/src/index.ts:395:12)
        at Module.load (module.js:566:32)
        at tryModuleLoad (module.js:506:12)
        at Function.Module._load (module.js:498:3)
```
    
 tried with :
both nodejs v11.15.0 and v8.16.2
npm: 6.4.1

**Comment by emiudeh** [comment]
Fixed this (on Linux mint) by running `sudo npm install -g gulp@3.9.1` instead of `npm install` on installation instruction 7.
